# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "USERS" ("USER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"USERNAME" VARCHAR NOT NULL,"PW_HASH" BLOB NOT NULL,"EMAIL" VARCHAR NOT NULL);

# --- !Downs

drop table "USERS";

