-- SQL DDL script
-- Generated file - do not edit

create table "GAMES" ("MATCH_ID" BIGINT NOT NULL,"DATE" BIGINT NOT NULL,"HERO_ID" INTEGER NOT NULL,"KILLS" INTEGER NOT NULL,"DEATHS" INTEGER NOT NULL,"ASSISTS" INTEGER NOT NULL,"GPM" INTEGER NOT NULL,"XPM" INTEGER NOT NULL,"WIN" BOOLEAN NOT NULL)

create table "HEROES" ("HERO_ID" INTEGER NOT NULL,"HERO_NAME" VARCHAR NOT NULL,"IMAGE_URL" VARCHAR NOT NULL)

create table "USERS" ("U_ID64" BIGINT NOT NULL PRIMARY KEY,"U_ID32" INTEGER NOT NULL,"U_NAME" VARCHAR NOT NULL)